### ISSUE TITLE
Unknown provider: atticoos.digitsProvider

### ISSUE THREAD

**Issue by guyschlider** [ajwhite/angular-digits#8]
Hi,
First, thanks for open-sourcing this!

I have a problem when I'm trying to use this module and to inject it to a controller I get:
Unknown provider: atticoos.digitsProvider

I'm pretty new to angular so maybe I'm not using it right, can I add it as a dependency to a controller without adding a dependency to the main app module?

I'm not adding it to the main app because it's trying to use window.Digits before the sdk is loaded.

  Thanks
Guy.

**Comment by atticoos** [comment]
It sounds like you need to include the module with the app.

Via the [README](https://github.com/ajwhite/angular-digits/blob/develop/README.md), you want to have something like the following:

``` js
angular.app('yourApp', ['atticoos.digits']) // inject the module

.controller('YourController', ['Digits', function (Digits] { // inject the service

})
```

---

Although it also sounds like the error

> Unknown provider: atticoos.digitsProvider

Might be due to the line `angular.app('yourApp', ['atticoos.digits'])`.

If that's the case and you do have it set up like this, then it sounds like a problem with the source code for this package not being properly included.

**Comment by guyschlider** [comment]
Thanks for the quick response man!

Hmm, When I'm i'm injecting It to the main app module I have another problem:
   TypeError: undefined is not an object (evaluating '$window.Digits.init')

I guess it because the Digits being loaded async, I will try to remove the async tag.
I thought that If I will inject it directly to the controller it will be ok (as the app is being inited before the digits load complete, but the controller happens afterwards)

**Comment by atticoos** [comment]
No problem!

> I guess it because the Digits being loaded async

This sounds spot on. If you remove the `async` attribute from the Digits script, you should be good.

I think I'll update the README with an example of loading the scripts properly since this will be a common issue, as [their documentation](https://docs.fabric.io/web/digits/getting-started.html) provides an example with the `async` attribute

**Comment by guyschlider** [comment]
Yes, the async was the problem. just tested and it works :+1: 
and yeah, updating the docs would be great.

Thanks again!

**Comment by atticoos** [comment]
Great!

**Comment by rojarohini** [comment]
still i am getting same error, may i know how o generate consumer key ? twitter consumer key is not working.
